'use client';
import { useState } from 'react';
import { productionHeaders } from '../projects/production-api';

type Proposal = { id: string; requestedChange: string; impact: Record<string, unknown>; riskLevel: string };
export function WorkflowConversation({ versionId, projectId }: { readonly versionId: string; readonly projectId: string }) {
  const [request, setRequest] = useState(''); const [proposal, setProposal] = useState<Proposal | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function propose() { if (!request.trim()) return; setBusy(true); setMessage(null); try { const response = await fetch(`/api/workflow-versions/${versionId}/change-proposals`, { method: 'POST', headers: productionHeaders({ 'Content-Type': 'application/json' }), body: JSON.stringify({ requestedChange: request.trim() }) }); const body = await response.json() as { proposal?: Proposal; error?: string }; if (!response.ok || !body.proposal) throw new Error(body.error ?? 'Unable to prepare a change proposal.'); setProposal(body.proposal); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to prepare a change proposal.'); } finally { setBusy(false); } }
  async function decide(decision: 'accept' | 'reject') { if (!proposal) return; setBusy(true); try { const response = await fetch(`/api/change-proposals/${proposal.id}/${decision}`, { method: 'POST', headers: productionHeaders() }); const body = await response.json() as { workflowVersionId?: string; error?: string }; if (!response.ok) throw new Error(body.error ?? 'Unable to decide this proposal.'); if (body.workflowVersionId) window.location.assign(`/workflow-versions/${body.workflowVersionId}/graph?projectId=${encodeURIComponent(projectId)}`); else { setProposal(null); setMessage('Proposal rejected. The workflow remains unchanged.'); } } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to decide this proposal.'); } finally { setBusy(false); } }
  return <section className="card"><h2>Change the workflow in plain language</h2><p className="muted">Tacit proposes a typed diff from the confirmed workflow only. It shows the impact first; accepting it creates a new draft version and makes prior builds stale.</p><textarea className="input" value={request} disabled={busy} onChange={(event) => setRequest(event.target.value)} placeholder="For example: Require human approval whenever the evidence conflicts, even if confidence is high." /><div className="header-actions" style={{ justifyContent: 'flex-start', marginTop: 12 }}><button className="btn btn-primary" disabled={busy || !request.trim()} onClick={() => void propose()}>{busy ? 'Preparing proposal…' : 'Propose change'}</button></div>{proposal ? <div className="card card-subtle" style={{ marginTop: 16 }}><span className="metric-label">Pending change proposal · {proposal.riskLevel} risk</span><p><strong>{proposal.requestedChange}</strong></p><pre className="json">{JSON.stringify(proposal.impact, null, 2)}</pre><div className="header-actions" style={{ justifyContent: 'flex-start' }}><button className="btn btn-primary" disabled={busy} onClick={() => void decide('accept')}>Accept and create new version</button><button className="btn btn-ghost" disabled={busy} onClick={() => void decide('reject')}>Reject</button></div></div> : null}{message ? <p className="notice" role="status">{message}</p> : null}</section>;
}
