'use client';

import type { ClarificationQuestion } from '@tacit/core-schemas';
import { useMemo, useState } from 'react';

function accessToken() { try { return (JSON.parse(window.sessionStorage.getItem('tacit.production.session') ?? 'null') as { accessToken?: string } | null)?.accessToken ?? null; } catch { return null; } }
function priority(question: ClarificationQuestion) { return question.riskIfUnanswered.toLowerCase().includes('unsafe') ? 'Critical' : question.relatedRuleId ? 'High' : 'Standard'; }

export function ClarificationInterview({ questions, onAnswer }: { readonly questions: readonly ClarificationQuestion[]; readonly onAnswer: (questionId: string, answer: unknown) => Promise<void> }) {
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [deferred, setDeferred] = useState<Record<string, boolean>>({}); const token = useMemo(accessToken, []); const openQuestions = questions.filter((question) => question.status === 'open');
  async function submit(question: ClarificationQuestion) { try { setError(null); const raw = answers[question.id] ?? ''; if (!raw) throw new Error('Provide an answer before continuing.'); await onAnswer(question.id, question.answerType === 'boolean' ? raw === 'true' : question.answerType === 'number' ? Number(raw) : raw); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save the answer.'); } }
  async function defer(question: ClarificationQuestion) { if (!token) { setError('Sign in to defer a clarification.'); return; } try { const response = await fetch(`/api/questions/${question.id}/assignment`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ deferReason: 'Waiting for an assigned subject-matter expert response.', attachmentExtractionIds: question.evidenceIds }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Unable to defer this clarification.'); setDeferred((current) => ({ ...current, [question.id]: true })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to defer this clarification.'); } }
  return <section aria-label="Clarification interview" className="stack"><section className="card card-subtle"><h2>Finish the knowledge transfer</h2><p className="muted">These are the decisions the AI could not resolve from the KT package alone. Questions are ranked by risk and rule impact. Answers create a new version; deferrals stay unresolved and keep affected actions supervised.</p></section>{openQuestions.length === 0 ? <section className="card"><p className="empty">No open clarifications remain. The workflow is ready to confirm.</p></section> : openQuestions.map((question, index) => <article className="card" key={question.id}><div className="card-header"><div><span className="metric-label">Priority {priority(question)} · Question {String(index + 1).padStart(2, '0')}</span><h2>{question.question}</h2></div><span className={`status ${priority(question) === 'Critical' ? 'status-danger' : 'status-warning'}`}>{deferred[question.id] ? 'Deferred' : 'Open decision'}</span></div><p>{question.rationale}</p><p className="muted"><strong style={{ color: 'var(--text)' }}>Rule impact:</strong> {question.relatedRuleId ? `This response changes the confirmation state for rule ${question.relatedRuleId}.` : 'This response constrains an unresolved workflow decision.'}</p><p className="muted"><strong style={{ color: 'var(--text)' }}>Evidence preview:</strong> {question.evidenceIds.length ? `${question.evidenceIds.length} cited source segment${question.evidenceIds.length === 1 ? '' : 's'} linked to this decision (${question.evidenceIds.join(', ')}).` : 'No direct source segment is available; keep this decision supervised.'}</p><p className="muted"><strong style={{ color: 'var(--text)' }}>Risk if unanswered:</strong> {question.riskIfUnanswered}</p><div className="header-actions" style={{ justifyContent: 'flex-start' }}>{question.answerType === 'boolean' || question.answerType === 'single_select' ? <select className="select" style={{ maxWidth: 360 }} value={answers[question.id] ?? ''} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })}><option value="">Choose an answer</option>{question.suggestedAnswers.map((answer) => <option key={answer.value} value={answer.value}>{answer.label}</option>)}</select> : <input className="input" style={{ maxWidth: 360 }} value={answers[question.id] ?? ''} type={question.answerType === 'number' ? 'number' : 'text'} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })} />}<button className="btn btn-primary" onClick={() => void submit(question)}>Confirm answer</button><button className="btn btn-ghost" onClick={() => void defer(question)} disabled={deferred[question.id]}>Defer to expert</button></div></article>)}{error && <p className="notice" role="alert">{error}</p>}</section>;
}
