'use client';

import { DemoControls } from './demo-controls';
import { StatusBadge, type ProductStatus } from './status-badge';
import { PageHeader, WorkspaceShell } from '../ui/app-shell';

interface OverviewMetric { readonly label: string; readonly value: string; }

export function DemoOverview({ projectId, projectName, metrics, status = 'needs_clarification' }: { readonly projectId: string; readonly projectName: string; readonly metrics: readonly OverviewMetric[]; readonly status?: ProductStatus }) {
  return <WorkspaceShell active="Overview" projectId={projectId} projectName={projectName}><PageHeader breadcrumb="Demo workspace" title={projectName} description="Turn expert judgment into a tested, reviewable workflow agent." status={<StatusBadge status={status} />} actions={<DemoControls stage="overview" />} /><div className="stack"><section className="card"><div className="card-header"><div><h2>Workflow readiness</h2><p className="muted">Follow the guided path to capture evidence, clarify decision boundaries, compile the agent, and verify its results.</p></div><a className="btn btn-primary" href={`/projects/${projectId}/observe`}>Begin observation</a></div><dl className="metric-grid">{metrics.map((metric) => <div className="card card-subtle metric-card" key={metric.label}><dt className="metric-label">{metric.label}</dt><dd className="metric-value">{metric.value}</dd><p className="metric-context">Current demo snapshot</p></div>)}</dl></section><section className="split"><article className="card"><h2>Current workflow stage</h2><ol className="progress-list"><li><div><strong>Observe expert review</strong><div className="muted">Capture structured actions and decision evidence.</div></div></li><li><div><strong>Clarify hidden rules</strong><div className="muted">Confirm ambiguous exceptions with the subject-matter expert.</div></div></li><li><div><strong>Compile and verify</strong><div className="muted">Generate constrained artifacts, then replay historical cases.</div></div></li></ol></article><article className="card"><h2>Safety boundary</h2><p className="muted">High-risk exceptions are held for human approval, with applied rules and evidence retained in the audit trail.</p><a href={`/projects/${projectId}/approvals`}>View approval queue →</a></article></section></div></WorkspaceShell>;
}
