import type { ApprovalAction, ApprovalRequest, ImpactMetrics } from '@tacit/core-schemas';
import type { ApprovalRepository } from './service';

type Row = Record<string, unknown>;
function config() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('Server persistence is not configured.'); return { url: url.replace(/\/$/, ''), key }; }
function requestRow(row: Row): ApprovalRequest { return { id: String(row.id), projectId: String(row.project_id), workflowVersionId: row.workflow_version_id ? String(row.workflow_version_id) : null, status: row.status as ApprovalRequest['status'], reason: String(row.reason), riskLevel: row.risk_level as ApprovalRequest['riskLevel'], requestedAction: String(row.requested_action), agentRecommendation: String(row.agent_recommendation), confidence: row.confidence === null ? null : Number(row.confidence), appliedRuleIds: (row.applied_rule_ids as string[]) ?? [], agentBuildId: row.agent_build_id ? String(row.agent_build_id) : null, evidenceIds: (row.evidence_ids as string[]) ?? [], payload: row.payload as Record<string, unknown>, createdAt: String(row.created_at) }; }
function impactRow(row: Row): ImpactMetrics { return { id: String(row.id), projectId: String(row.project_id), workflowVersionId: row.workflow_version_id ? String(row.workflow_version_id) : null, observedCases: Number(row.observed_cases), automationCoveragePercent: Number(row.automation_coverage_percent), accuracyPercent: Number(row.accuracy_percent), estimatedMinutesSaved: Number(row.estimated_minutes_saved), manualSteps: Number(row.manual_steps), automatedSteps: Number(row.automated_steps), aiAssistedSteps: Number(row.ai_assisted_steps), humanRequiredSteps: Number(row.human_required_steps), manualHandlingMinutes: Number(row.manual_handling_minutes), estimatedAutomatedMinutes: Number(row.estimated_automated_minutes), reviewRatePercent: Number(row.review_rate_percent), rulesDiscovered: Number(row.rules_discovered), undocumentedExceptions: Number(row.undocumented_exceptions), sources: row.sources as ImpactMetrics['sources'], assumptions: (row.assumptions as string[]) ?? [], capturedAt: String(row.captured_at) }; }

export class SupabaseApprovalRepository implements ApprovalRepository {
  private readonly connection = config();
  private async request(path: string, init: RequestInit = {}) { const response = await fetch(`${this.connection.url}/rest/v1/${path}`, { ...init, headers: { apikey: this.connection.key, Authorization: `Bearer ${this.connection.key}`, 'Content-Type': 'application/json', ...(init.headers ?? {}) } }); if (!response.ok) throw new Error(`Approval persistence failed (${response.status}).`); const text = await response.text(); return text ? JSON.parse(text) : null; }
  async list(projectId: string) { const rows = await this.request(`approval_requests?project_id=eq.${encodeURIComponent(projectId)}&select=*&order=created_at.desc`) as Row[]; return rows.map(requestRow); }
  async get(id: string) { const rows = await this.request(`approval_requests?id=eq.${encodeURIComponent(id)}&select=*&limit=1`) as Row[]; return rows[0] ? requestRow(rows[0]) : null; }
  async saveRequest(input: Omit<ApprovalRequest, 'id'>, requestedBy?: string) { const rows = await this.request('approval_requests', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify([{ project_id: input.projectId, workflow_version_id: input.workflowVersionId, status: input.status, reason: input.reason, risk_level: input.riskLevel, requested_action: input.requestedAction, agent_recommendation: input.agentRecommendation, confidence: input.confidence, applied_rule_ids: input.appliedRuleIds, agent_build_id: input.agentBuildId, evidence_ids: input.evidenceIds, payload: input.payload, created_at: input.createdAt, requested_by: requestedBy ?? null }]) }) as Row[]; return requestRow(rows[0]); }
  async saveAction(input: Omit<ApprovalAction, 'id' | 'actedAt'>) { const actedAt = new Date().toISOString(); const rows = await this.request('approval_actions', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify([{ approval_request_id: input.approvalRequestId, decision: input.decision, comment: input.comment, approver: input.approver, actor_id: input.actorId, acted_at: actedAt }]) }) as Row[]; const row = rows[0]; return { id: String(row.id), approvalRequestId: String(row.approval_request_id), decision: row.decision as ApprovalAction['decision'], comment: row.comment ? String(row.comment) : null, approver: String(row.approver), actorId: row.actor_id ? String(row.actor_id) : null, actedAt: String(row.acted_at) }; }
  async updateStatus(id: string, status: ApprovalRequest['status']) { await this.request(`approval_requests?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify({ status }) }); }
  async latestImpact(projectId: string) { const rows = await this.request(`impact_snapshots?project_id=eq.${encodeURIComponent(projectId)}&select=*&order=captured_at.desc&limit=1`) as Row[]; return rows[0] ? impactRow(rows[0]) : null; }
}
